redirects: {}
# redirect.host: https://redirect/url
# ^redirect.host/path$: https://redirect/url

proxy_real_ip_from: []
#  - 192.168.0.0/16

nameOverride: ""
fullnameOverride: ""

deployment:
  image:
    registry: ""
    repository: nginx
    tag: "" # Defaults to Release.AppVersion-alpine
    digest: ""
    pullPolicy: IfNotPresent

  labels: {}
  annotations: {}
  podLabels: {}

  resourcesPreset: nano
  resources: {}

ingress:
  enabled: false

  annotations: {}
  hosts: []
  tls: []
