{{- if .Values.proxy.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "lemmy.service.fullname" (dict "name" "proxy" "context" .) | quote }}
  {{- with .Values.proxy.ingress.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.proxy.ingress.ingressClassName }}
  ingressClassName: {{ quote . }}
  {{- end }}

  rules:
    {{- range .Values.proxy.ingress.hosts }}
    - host: {{ quote . }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "lemmy.service.fullname" (dict "name" "proxy" "context" $) | quote }}
                port:
                  name: http
          {{- range list "/api" "/pictrs" "/feeds" "/nodeinfo" "/.well-known" }}
          - path: {{ quote . }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "lemmy.service.fullname" (dict "name" "server" "context" $) | quote }}
                port:
                  name: http
          {{- end }}
    {{- end }}
  {{- with .Values.proxy.ingress.tls }}
  tls: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
