---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lemmy.service.fullname" (dict "name" "server" "context" .) | quote }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "common.labels.matchLabels" (dict "customLabels" .Values.server.labels "context" $) | nindent 6 }}
      service: server
  template:
    metadata:
      annotations:
        checksum/server-config: {{ include "common.utils.checksumTemplate" (dict "path" "/server/configmap.yaml" "context" $) | quote }}
        {{- with .Values.server.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels: {{- include "common.labels.standard" (dict "customLabels" .Values.server.labels "context" $) | nindent 8 }}
        service: server
    spec:
      containers:
        - name: {{ include "lemmy.service.fullname" (dict "name" "server" "context" .) | quote }}
          image: {{ include "common.images.image" ( dict "imageRoot" (merge .Values.server.image (dict "tag" .Chart.AppVersion)) ) | quote }}
          imagePullPolicy: {{ quote .Values.server.image.pullPolicy }}
          env:
            {{- with .Values.server.config.database.uriSecret }}
            - name: LEMMY_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ quote . }}
                  key: "uri"
            {{- end }}
            {{- with .Values.server.config.email.smtp.passwordSecret }}
            - name: LEMMY_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ quote . }}
                  key: "password"
            {{- end }}
          {{- with .Values.server.env }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.server.envFrom }}
          envFrom: {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 8536
              name: http
              protocol: TCP
            - containerPort: 8080
              name: metrics
              protocol: TCP
          {{- with .Values.server.podSecurityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.server.config.enabled .Values.server.volumeMounts }}
          volumeMounts:
            {{- if .Values.server.config.enabled }}
            - name: config
              mountPath: /config/config.hjson
              subPath: config.hjson
            {{- end }}
            {{- with .Values.server.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
      {{- if or .Values.server.config.enabled .Values.server.volumes }}
      volumes:
        {{- if .Values.server.config.enabled }}
        - name: config
          configMap:
            name: {{ include "lemmy.service.fullname" (dict "name" "server" "context" .) | quote }}
        {{- end }}
        {{- with .Values.server.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
