{{- if .Values.ui.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lemmy.service.fullname" (dict "name" "ui" "context" .) | quote }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "common.labels.matchLabels" (dict "customLabels" .Values.ui.labels "context" $) | nindent 6 }}
      service: lemmy-ui
  template:
    metadata:
      {{- with .Values.ui.annotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" (dict "customLabels" .Values.ui.labels "context" $) | nindent 8 }}
        service: lemmy-ui
    spec:
      containers:
        - name: {{ include "lemmy.service.fullname" (dict "name" "ui" "context" .) | quote }}
          image: {{ include "common.images.image" ( dict "imageRoot" (merge .Values.ui.image (dict "tag" .Chart.AppVersion)) ) | quote }}
          imagePullPolicy: {{ quote .Values.ui.image.pullPolicy }}
          env:
            - name: LEMMY_UI_LEMMY_INTERNAL_HOST
              value: {{ include "lemmy.service.fullname" (dict "name" "server" "context" .) | quote }}
            {{- with .Values.ui.external.host }}
            - name: LEMMY_UI_LEMMY_EXTERNAL_HOST
              value: {{ quote . }}
            {{- end }}
            {{- if .Values.ui.external.https }}
            - name: LEMMY_HTTPS
              value: "true"
            {{- end }}
            {{- with .Values.ui.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.ui.envFrom }}
          envFrom: {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 1234
              name: http
              protocol: TCP
          {{- if .Values.ui.resources }}
          resources: {{- toYaml .Values.ui.resources | nindent 12 }}
          {{- else if ne .Values.ui.resourcesPreset "none" }}
          resources: {{- include "common.resources.preset" (dict "type" .Values.ui.resourcesPreset) | nindent 12 }}
          {{- end }}
          {{- with .Values.ui.podSecurityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ui.volumeMounts }}
          volumeMounts: {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.ui.volumes }}
      volumes: {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
