{{- if .Values.ui.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lemmy.service.fullname" (dict "name" "ui" "context" .) | quote }}
spec:
  selector: {{- include "common.labels.matchLabels" (dict "customLabels" .Values.ui.labels "context" $) | nindent 4 }}
    service: lemmy-ui
  ports:
    - name: http
      port: 80
      targetPort: http
{{- end }}
