{{- $files := .Files.Glob "nginx-templates/*" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-templates
data:
{{- range $filename, $content := $files }}
  {{ base $filename }}: | {{- tpl ($content | toString) $ | nindent 4 }}
{{- end }}
