{{- if or .Values.service.enabled .Values.ingress.enabled .Values.proxy.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "voyager.service.fullname" (dict "name" "ui" "context" .) | quote }}
spec:
  selector: {{- include "common.labels.matchLabels" (dict "customLabels" .Values.labels "context" $) | nindent 4 }}
    service: voyager-ui
  ports:
    - name: http
      port: 80
      targetPort: http
{{- end }}
