apiVersion: v2
name: lemmy
description: lemmy
type: application
version: v0.1.4
# renovate: image=dessalines/lemmy
appVersion: 0.19.7
dependencies:
  - name: common
    repository: 'oci://registry-1.docker.io/bitnamicharts'
    version: '2.28.0'
