apiVersion: v2
name: lemmy
description: lemmy
type: application
version: v0.3.0
# renovate: image=dessalines/lemmy
appVersion: 0.19.9
dependencies:
  - name: common
    repository: 'oci://registry-1.docker.io/bitnamicharts'
    version: '2.29.1'
