{{- if or .Values.service.enabled .Values.ingress.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . | quote }}
spec:
  selector: {{- include "common.labels.matchLabels" (dict "customLabels" .Values.labels "context" $) | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
{{- end }}
