---
image:
  registry: ghcr.io
  repository: aeharding/voyager
  tag: "" # Defaults to Release.AppVersion
  digest: ""
  pullPolicy: IfNotPresent

lemmyServers: []

labels: {}
env: []
envFrom: []

ingress:
  enabled: false
  ingressClassName: ""
  annotations: {}
  hosts: []
  tls: []

service:
  enabled: false

resourcesPreset: nano
resources: {}

proxy:
  enabled: false

  image:
    registry: ""
    repository: nginx
    tag: "1-alpine"
    digest: ""
    pullPolicy: IfNotPresent

  config:
    enabled: true

    lemmyServer: ""
    allowedProxies: []

  labels: {}

  ingress:
    enabled: false
    ingressClassName: ""
    annotations: {}
    hosts: []
    tls: []

  resourcesPreset: nano
  resources: {}
