name: Release Helm

on:
  push:
    tags:
      - '*/v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.10.0

      - name: Login to mrmhub
        run: |
          echo '${{ secrets.MRMHUB_PASSWORD }}' | helm registry login mrmhub.io --username '${{ secrets.MRMHUB_USERNAME }}' --password-stdin
      
      - name: Configure chart version
        id: chart_meta
        run: |
          cat >> "$GITHUB_OUTPUT" <<EOF
          chart_name=$(cut -d / -f 3 <<<"${{ github.ref }}")
          chart_version=$(cut -d / -f 4- <<<"${{ github.ref }}")
          EOF

      - name: Package chart
        run: |
          helm package "${{ steps.chart_meta.outputs.chart_name }}" --version "${{ steps.chart_meta.outputs.chart_version }}"

      - name: Upload chart
        run: |
          helm push "${{ steps.chart_meta.outputs.chart_name }}-${{ steps.chart_meta.outputs.chart_version }}.tgz" oci://mrmhub.io/mikemrm
